---

- hosts: all
  become: true
  remote_user: ubuntu

  tasks:

    - name: updating servers
      apt: 
        update_cache: yes
        upgrade: yes

    - name: installing apache2
      apt:
        name: 
        - apache2
        state: present

    - name: Setting timezone to Africa/Lagos
      timezone:
        name: Africa/Lagos

    - name: Printing hostname on server
      shell: echo "<h1>Welcome to $(hostname -f). Today's date and time in Lagos, Nigeria is $(date)</h1>" > /var/www/html/index.html

    - name: restart apache2
      service:
        name: apache2
        state: restarted
